### ISSUE TITLE
你好，我下载了该项目，已经安装好node_modules，可是使用npm start 无法启动，报错

### ISSUE THREAD

**Issue by jiajia-tao** [ahyiru/web-design#1]
![image](https://user-images.githubusercontent.com/70623063/232353873-5c929f94-e7ad-4add-aaa2-a7870b8744f2.png)

**Comment by ahyiru** [comment]
是 `npm start --dirname=app`，[huxy-admin](https://github.com/ahyiru/huxy-admin) 文档里多写了一个 `-`。启动 `app` 目录直接 `npm start` 就行了。

**Comment by jiajia-tao** [comment]
你好，我是在vscode终端启动项目的，还是无法成功，请问你这边得空能写一篇启动文章吗？

**Comment by ahyiru** [comment]
> 你好，我是在vscode终端启动项目的，还是无法成功，请问你这边得空能写一篇启动文章吗？

可能是打包工具没兼容windows，已经升级了打包工具。工程化配置可参考 [@huxy/pack](https://github.com/ahyiru/pack/blob/main/README.md) 。
